url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Rimenes Ribeiro" # the name of your site, e.g. ACME Corp.

google_analytics: UA-1607568-18

plugins:
  - jekyll-postcss
  - jekyll-purgecss
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-last-modified-at

css_dir: "assets/css"

social:
  name: Rimenes Ribeiro
  links:
    - https://twitter.com/rimenes
    - https://linkedin.com/in/rimenes
    - https://github.com/rimenes
    - https://keybase.io/rimenes

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - yarn.lock
  - postcss.config.js
  - purgecss.config.js
  - tailwind.config.js
  - LICENSE
  - README.md
