url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.

google_analytics: UA-1607568-18

plugins:
  - jekyll-postcss
  - jekyll-purgecss
  - jekyll-sitemap

css_dir: "assets/css"
